# Generated by Django 3.0.7 on 2020-11-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20201102_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
