# Generated by Django 3.1.3 on 2020-11-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20201102_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Antiques', 'Antiques'), ('Clothes', 'Clothes'), ('Decoration', 'Decoration'), ('Electronics', 'Electronics'), ('Other', 'Other'), ('Valuables', 'Valueables')], default='Other', max_length=11),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sold', 'Sold')], default='Pending', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
