# Generated by Django 3.1.3 on 2020-11-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Antiques', 'Antiques'), ('Clothes', 'Clothes'), ('Decoration', 'Decoration'), ('Electronics', 'Electronics'), ('Valuables', 'Valueables'), ('Other', 'Other')], default='Other', max_length=11),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='uploads/None/NIA.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=7),
        ),
    ]
