# Generated by Django 3.1.3 on 2020-11-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201105_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='None/NIA.png', upload_to=''),
        ),
    ]
